steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-a', '-installsuffix', 'cgo', '-o', 'build/server']
  env:
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/$PROJECT_ID/$TAG_NAME', '-f', 'deploy/Dockerfile']

artifacts:
  objects:
    location: gs://$PROJECT_ID_cloudbuild/bin/
    paths:
    - build/server
images:
- 'gcr.io/$PROJECT_ID/$TAG_NAME'